Version 4
SymbolType BLOCK
LINE Normal -12 -32 28 -16
LINE Normal 64 -16 36 -16
LINE Normal -48 -32 -20 -32
LINE Normal -48 0 -20 0
LINE Normal 1 -32 -12 -32
LINE Normal -2 -23 1 -32
LINE Normal -12 -32 -2 -23
CIRCLE Normal -12 -28 -20 -36
CIRCLE Normal -12 4 -20 -4
CIRCLE Normal 36 -12 28 -20
PIN -48 -32 NONE 8
PINATTR PinName 1
PINATTR SpiceOrder 1
PIN -48 0 NONE 8
PINATTR PinName 2
PINATTR SpiceOrder 2
PIN 64 -16 NONE 8
PINATTR PinName 3
PINATTR SpiceOrder 3
